filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - C:\\Workspace\\projects\\opensearch\\weblogic-logs-*.log
    fields_under_root: true

processors:
  - dissect:
      field: "log.file.path"  # Use the correct field name for the file path
      tokenizer: "C:\\Workspace\\projects\\opensearch\\weblogic-logs-%{log_date}.log"
      target_prefix: "dissect"
  - rename:
      fields:
        - from: "dissect.log_date"
          to: "logfile"

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "admin"
  password: "mypassword"
  ssl.verification_mode: none
  index: "weblogic-logs-%{[logfile]}"  # Use the extracted `logfile` value

setup.template.name: "weblogic-logs"
setup.template.pattern: "weblogic-logs-*"
setup.ilm.enabled: false

setup.kibana:
  host: "https://localhost:5601"

logging.level: debug
logging.to_files: true
logging.files:
  path: C:/Workspace/projects/opensearch/log/filebeat
  name: filebeat.log
  keepfiles: 7